spring:
  application:
    name: kedSpringbootApp
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://user:password@192.168.1.50:27017/learningDB?authSource=learningDB}
      database: learningDB
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy

server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui.html