spring:
  application:
    name: kedSpringbootApp
  data:
    mongodb:
#      host: 192.168.1.50 # Use your actual IP here
#      port: 27107
#      database: learningDB
#      username: devUser
#      password: Mango_01!
      uri: mongodb://devUser:Mango_01!@192.168.1.50:27017/learningDB
      database: learningDB
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy

springdoc:
  swagger-ui:
    path: /swagger-ui.html